[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 120 # Default is usually 88, setting it higher initially.
target-version = ['py311'] # Apparently this is what freecad supports.

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 120 # Default is usually 88, setting it higher initially.