name: CI

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint & Format Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort

    - name: Check code formatting with Black
      run: |
        black --check .

    - name: Check import sorting with isort
      run: |
        isort --check-only .